/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wang_a1ex_android_4over6_VpnDevices */

#ifndef _Included_wang_a1ex_android_4over6_VpnDevices
#define _Included_wang_a1ex_android_4over6_VpnDevices
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wang_a1ex_android_4over6_VpnDevices
 * Method:    startVpn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_wang_a1ex_android_14over6_VpnDevices_startVpn
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
