/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wang_a1ex_android_4over6_VpnDevices_VpnCallbacks */

#ifndef _Included_wang_a1ex_android_4over6_VpnDevices_VpnCallbacks
#define _Included_wang_a1ex_android_4over6_VpnDevices_VpnCallbacks
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
