/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wang_a1ex_android_4over6_NdkUtil */

#ifndef _Included_wang_a1ex_android_4over6_NdkUtil
#define _Included_wang_a1ex_android_4over6_NdkUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wang_a1ex_android_4over6_NdkUtil
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wang_a1ex_android_14over6_NdkUtil_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
